name: CI

on:
  push:
    branches:
      - "*"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.x"
        source-dir-path:
          - "./krennic"
        tests-dir-path:
          - "./tests"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Format
        run: |
          python -m black --check ${{ matrix.source-dir-path }}
  
      - name: Lint
        run: |
          python -m flake8 ${{ matrix.source-dir-path }}
        # Assumes flake8 in requirements.txt

      - name: Test
        run: |
          python -m pytest ${{ matrix.tests-dir-path }}
        # Assumes pytest, pytest-benchmark, pytest-cov in requirements.txt
